In [1]:
from bs4 import BeautifulSoup
import requests
import re
import pandas as pd

In [2]:
def current_movies_in():
    l=[]
    response = requests.get('https://www.imdb.com/showtimes/?ref_=shlc_sh')
    a = BeautifulSoup(response.text, "html.parser")
    k=a.find_all("a", itemprop="url")
    base="https://www.imdb.com/showtimes/title"
    base1="?ref_=sh_ov_tt"
    for i in range(len(k)):
        x=re.findall('/tt\w+',str(k[i]))
        if x:
            if x[0] not in l:
                l.append(x[0])
    d={}
    for i in l:
        p=[]
        q=[]
        new_link=base+i+base1
        response = requests.get(new_link)
        a = BeautifulSoup(response.text, "html.parser")
        k=a.find_all("a", itemprop="url")
        for j in k:
            if '/ci' in str(j):
                x=re.findall('/ci\w+',str(j))
                if x:
                    p.append(j.text)
        d[i]=p
    base='https://www.imdb.com/title'
    base1='/reviews/?ref_=tt_ql_2'
    link,con,title,date,name,rate,d1=[],[],[],[],[],[],{}
    for i in l:
        new_link=base+i+base1
        response = requests.get(new_link)
        a = BeautifulSoup(response.text, "html.parser")
        rev=a.find_all(class_='text show-more__control')
        rev1=a.find_all(class_='title')
        rev2=a.find_all(class_='review-date')
        rev3=a.find_all(class_='display-name-link')
        rev4=a.find_all('a',itemprop='url')
        rev5=a.find_all('span',class_='rating-other-user-rating')
        for w in rev4:
            d1[i]=w.text
        for p,j,k,n,o in zip(rev,rev1,rev2,rev3,rev5):
            con.append(p.text)
            title.append(j.text)
            date.append(k.text)
            name.append(n.text)
            rate.append(o.text)
        link+=[i]*len(rev5)
    df=pd.DataFrame({'ID':link,'Name':name,'Date':date,'Title':title,'Review':con,'Rating':rate})

    mv=[]
    th=[]
    for i in range(len(df)):
        for j in d1:
            if df['ID'][i]==j:
                mv.append(d1[j])
        for j in d:
            if df['ID'][i]==j:
                th.append(d[j])
    df['Movie Name']=mv
    df['Theatres']=th
    return df

In [3]:
df=current_movies_in()
df

,ID,Name,Date,Title,Review,Rating,Movie Name,Theatres
0,/tt1517268,Imshortok06,23 July 2023,Creative but preachy and confusing\n,I'm just going to get straight to the point: I...,\n\n\n\n\n\n6/10\n,Barbie,"[INOX Eros One, INOX Odeon Connaught Place, PV..."
1,/tt1517268,LoveofLegacy,21 July 2023,"Beautiful film, but so preachy\n","Margot does the best with what she's given, bu...",\n\n\n\n\n\n6/10\n,Barbie,"[INOX Eros One, INOX Odeon Connaught Place, PV..."
2,/tt1517268,Lk1990,24 July 2023,"High Highs, Low Lows.\n",The first thing you need to know about Barbie ...,\n\n\n\n\n\n6/10\n,Barbie,"[INOX Eros One, INOX Odeon Connaught Place, PV..."
3,/tt1517268,ramair350,31 July 2023,"As a guy I felt some discomfort, and that's o...",As much as it pains me to give a movie called ...,\n\n\n\n\n\n10/10\n,Barbie,"[INOX Eros One, INOX Odeon Connaught Place, PV..."
4,/tt1517268,coxaneesa,24 July 2023,It was depressing\n,I thought this would be so much different. The...,\n\n\n\n\n\n8/10\n,Barbie,"[INOX Eros One, INOX Odeon Connaught Place, PV..."
...,...,...,...,...,...,...,...,...
333,/tt6718170,keystone_koasters,5 April 2023,Solid\n,"As a Super Mario fan myself, I was hyping this...",\n\n\n\n\n\n7/10\n,The Super Mario Bros. Movie,[PVR Logix Noida]
334,/tt6718170,namob-43673,18 April 2023,"Bad music, simplistic story, lazy writing, bu...",The headline basically tells the story. This i...,\n\n\n\n\n\n5/10\n,The Super Mario Bros. Movie,[PVR Logix Noida]
335,/tt6718170,javier_8,14 April 2023,The movie I wish I had when I was a kid.\n,"First of all: This is A MOVIE FOR KIDS, it's n...",\n\n\n\n\n\n9/10\n,The Super Mario Bros. Movie,[PVR Logix Noida]
336,/tt6718170,erick-hernandez,5 April 2023,Fan Service Done RIGHT!\n,"There are some very minor spoilers ahead, i ju...",\n\n\n\n\n\n10/10\n,The Super Mario Bros. Movie,[PVR Logix Noida]
337,/tt6718170,TheMustardNerd,7 May 2023,Let's a go fast\n,"This is gonna be one of my shorter reviews, si...",\n\n\n\n\n\n3/10\n,The Super Mario Bros. Movie,[PVR Logix Noida]

In [4]:
df.to_csv('Movie_Review.csv')

In [6]:
df[df['Movie Name']=='DD Returns']

,ID,Name,Date,Title,Review,Rating,Movie Name,Theatres
196,/tt27510150,prithiviramthirupathy,30 July 2023,Must Watch Family Entertainment Hor-Com\n,Very good quality Horror Comedy. Stun us with ...,\n\n\n\n\n\n10/10\n,DD Returns,"[PVR Naraina, PVR Logix Noida]"
197,/tt27510150,vigneshraj,30 July 2023,A must watch Horror comedy drama 👏 😂\n,"What a fun filled ride , entirely enjoyable mo...",\n\n\n\n\n\n10/10\n,DD Returns,"[PVR Naraina, PVR Logix Noida]"

In [9]:
df1=pd.read_csv(r"C:\Users\aashi\Downloads\Movie_Review (1).csv")
df1

,Unnamed: 0,ID,Name,Date,Title,Review,Movie Name,Theatres
0,0,/tt27510150,prithiviramthirupathy,30 July 2023,Must Watch Family Entertainment Hor-Com\n,Very good quality Horror Comedy. Stun us with ...,DD Returns,"['Bharath Theatre', 'Devi Multiplex - Chennai'..."
1,1,/tt27510150,vigneshraj,30 July 2023,A must watch Horror comedy drama 👏 😂\n,"What a fun filled ride , entirely enjoyable mo...",DD Returns,"['Bharath Theatre', 'Devi Multiplex - Chennai'..."
2,2,/tt26459508,art3mi5,31 July 2023,"A fun, entertaining movie with an excellent u...",This movie checked all the boxes for me with a...,Let's Get Married,"['Bharath Theatre', 'Devi Multiplex - Chennai'..."
3,3,/tt26459508,prolead,30 July 2023,Good clean family entertainer\n,Hard to believe this is a movie by a first tim...,Let's Get Married,"['Bharath Theatre', 'Devi Multiplex - Chennai'..."
4,4,/tt26459508,rani1960,1 August 2023,"Fun, feel-good family flick!!\n","A clean family entertainer. Well directed, wel...",Let's Get Married,"['Bharath Theatre', 'Devi Multiplex - Chennai'..."
...,...,...,...,...,...,...,...,...
390,390,/tt6718170,keystone_koasters,5 April 2023,Solid\n,"As a Super Mario fan myself, I was hyping this...",The Super Mario Bros. Movie,['PVR Heritage RSL ECR Chennai']
391,391,/tt6718170,namob-43673,18 April 2023,"Bad music, simplistic story, lazy writing, bu...",The headline basically tells the story. This i...,The Super Mario Bros. Movie,['PVR Heritage RSL ECR Chennai']
392,392,/tt6718170,javier_8,14 April 2023,The movie I wish I had when I was a kid.\n,"First of all: This is A MOVIE FOR KIDS, it's n...",The Super Mario Bros. Movie,['PVR Heritage RSL ECR Chennai']
393,393,/tt6718170,erick-hernandez,5 April 2023,Fan Service Done RIGHT!\n,"There are some very minor spoilers ahead, i ju...",The Super Mario Bros. Movie,['PVR Heritage RSL ECR Chennai']
394,394,/tt6718170,TheMustardNerd,7 May 2023,Let's a go fast\n,"This is gonna be one of my shorter reviews, si...",The Super Mario Bros. Movie,['PVR Heritage RSL ECR Chennai']

In [10]:
df=pd.read_csv(r'Movie_Review.csv')
df

,Unnamed: 0,ID,Name,Date,Title,Review,Rating,Movie Name,Theatres
0,0,/tt1517268,Imshortok06,23 July 2023,Creative but preachy and confusing\n,I'm just going to get straight to the point: I...,\n\n\n\n\n\n6/10\n,Barbie,"['INOX Eros One', 'INOX Odeon Connaught Place'..."
1,1,/tt1517268,LoveofLegacy,21 July 2023,"Beautiful film, but so preachy\n","Margot does the best with what she's given, bu...",\n\n\n\n\n\n6/10\n,Barbie,"['INOX Eros One', 'INOX Odeon Connaught Place'..."
2,2,/tt1517268,Lk1990,24 July 2023,"High Highs, Low Lows.\n",The first thing you need to know about Barbie ...,\n\n\n\n\n\n6/10\n,Barbie,"['INOX Eros One', 'INOX Odeon Connaught Place'..."
3,3,/tt1517268,ramair350,31 July 2023,"As a guy I felt some discomfort, and that's o...",As much as it pains me to give a movie called ...,\n\n\n\n\n\n10/10\n,Barbie,"['INOX Eros One', 'INOX Odeon Connaught Place'..."
4,4,/tt1517268,coxaneesa,24 July 2023,It was depressing\n,I thought this would be so much different. The...,\n\n\n\n\n\n8/10\n,Barbie,"['INOX Eros One', 'INOX Odeon Connaught Place'..."
...,...,...,...,...,...,...,...,...,...
333,333,/tt6718170,keystone_koasters,5 April 2023,Solid\n,"As a Super Mario fan myself, I was hyping this...",\n\n\n\n\n\n7/10\n,The Super Mario Bros. Movie,['PVR Logix Noida']
334,334,/tt6718170,namob-43673,18 April 2023,"Bad music, simplistic story, lazy writing, bu...",The headline basically tells the story. This i...,\n\n\n\n\n\n5/10\n,The Super Mario Bros. Movie,['PVR Logix Noida']
335,335,/tt6718170,javier_8,14 April 2023,The movie I wish I had when I was a kid.\n,"First of all: This is A MOVIE FOR KIDS, it's n...",\n\n\n\n\n\n9/10\n,The Super Mario Bros. Movie,['PVR Logix Noida']
336,336,/tt6718170,erick-hernandez,5 April 2023,Fan Service Done RIGHT!\n,"There are some very minor spoilers ahead, i ju...",\n\n\n\n\n\n10/10\n,The Super Mario Bros. Movie,['PVR Logix Noida']
337,337,/tt6718170,TheMustardNerd,7 May 2023,Let's a go fast\n,"This is gonna be one of my shorter reviews, si...",\n\n\n\n\n\n3/10\n,The Super Mario Bros. Movie,['PVR Logix Noida']

In [13]:
for i in range(len(df)):
    for j in range(len(df1)):
        if df['Movie Name'][i]==df1['Movie Name'][j]:
            df['Theatres'][i]=df1['Theatres'][j]
df

C:\Users\aashi\AppData\Local\Temp/ipykernel_13808/258673220.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Theatres'][i]=df1['Theatres'][j]

,Unnamed: 0,ID,Name,Date,Title,Review,Rating,Movie Name,Theatres
0,0,/tt1517268,Imshortok06,23 July 2023,Creative but preachy and confusing\n,I'm just going to get straight to the point: I...,\n\n\n\n\n\n6/10\n,Barbie,"['INOX Chennai', 'SPI Cinemas Sathyam Chennai'..."
1,1,/tt1517268,LoveofLegacy,21 July 2023,"Beautiful film, but so preachy\n","Margot does the best with what she's given, bu...",\n\n\n\n\n\n6/10\n,Barbie,"['INOX Chennai', 'SPI Cinemas Sathyam Chennai'..."
2,2,/tt1517268,Lk1990,24 July 2023,"High Highs, Low Lows.\n",The first thing you need to know about Barbie ...,\n\n\n\n\n\n6/10\n,Barbie,"['INOX Chennai', 'SPI Cinemas Sathyam Chennai'..."
3,3,/tt1517268,ramair350,31 July 2023,"As a guy I felt some discomfort, and that's o...",As much as it pains me to give a movie called ...,\n\n\n\n\n\n10/10\n,Barbie,"['INOX Chennai', 'SPI Cinemas Sathyam Chennai'..."
4,4,/tt1517268,coxaneesa,24 July 2023,It was depressing\n,I thought this would be so much different. The...,\n\n\n\n\n\n8/10\n,Barbie,"['INOX Chennai', 'SPI Cinemas Sathyam Chennai'..."
...,...,...,...,...,...,...,...,...,...
333,333,/tt6718170,keystone_koasters,5 April 2023,Solid\n,"As a Super Mario fan myself, I was hyping this...",\n\n\n\n\n\n7/10\n,The Super Mario Bros. Movie,['PVR Heritage RSL ECR Chennai']
334,334,/tt6718170,namob-43673,18 April 2023,"Bad music, simplistic story, lazy writing, bu...",The headline basically tells the story. This i...,\n\n\n\n\n\n5/10\n,The Super Mario Bros. Movie,['PVR Heritage RSL ECR Chennai']
335,335,/tt6718170,javier_8,14 April 2023,The movie I wish I had when I was a kid.\n,"First of all: This is A MOVIE FOR KIDS, it's n...",\n\n\n\n\n\n9/10\n,The Super Mario Bros. Movie,['PVR Heritage RSL ECR Chennai']
336,336,/tt6718170,erick-hernandez,5 April 2023,Fan Service Done RIGHT!\n,"There are some very minor spoilers ahead, i ju...",\n\n\n\n\n\n10/10\n,The Super Mario Bros. Movie,['PVR Heritage RSL ECR Chennai']
337,337,/tt6718170,TheMustardNerd,7 May 2023,Let's a go fast\n,"This is gonna be one of my shorter reviews, si...",\n\n\n\n\n\n3/10\n,The Super Mario Bros. Movie,['PVR Heritage RSL ECR Chennai']

In [14]:
df.to_csv('Final Movie_Review.csv')

In [ ]:
#Genre categorization - age group of people , what type-family,adult, suggest theatre
#nearby theatre and what movies are there